name: MeteorMod
main: com.github.dublekfx.MeteorMod.MeteorMod
version: 1.0
commands:
  meteor:
    description: "For I am become Death, Destroyer of Worlds"
    usage: /meteor (Use /meteormod to specify a target and radius!)
    permission: meteor.launch
    permission-message: You are not Shiva!
  meteormod:
    description: "The Reckoning has arrived"
    usage: /meteormod <p:player> <m:material> <r:radius> <e:blockdamage(true/false)> <c:countdown> 
    permission: meteor.launch
    permission-message: You are not Shiva!
  countdown:
    description: Experience Timer
    usage: /countdown <duration>
  startreckoning:
    description: Making it rain
    usage: /startreckoning
    permission: meteor.launch
    permission-message: You are not Shiva!
  stopreckoning:
    description: Clearing the skies
    usage: /stopreckoning
    permission: meteor.launch
    permission-message: You are not Shiva!
permissions:
  meteor.launch:
    description: Permits the user to reign justice down upon his enemies.
    default: op