name: MeteorMod
main: com.github.dublekfx.Meteor.MeteorMod
version: 1.0
commands:
  meteor:
    description: "For I am become Death, Destroyer of Worlds"
    usage: /meteor (Use /meteormod to specify a target and radius!)
    permission: meteor.launch
    permission-message: You are not Shiva!
  meteormod:
    description: "The Reckoning has arrived"
    usage: /meteormod <player> <radius>
    permission: meteor.launch
    permission-message: You are not Shiva!
permissions:
  meteor.launch:
    description: Permits the user to reign justice down upon his enemies.
    default: op